### ISSUE TITLE
Need help in documentation

### ISSUE THREAD

**Issue by AnujaKadloor** [SmartBear/one-report-publisher#15]
Hi,

This isn't an issue but I don't know where do I ask this question.
I'm using TestComplete to automate Desktop application and Github actions as the CI/CD tool.
While searching for a reporting plugin for TestComplete thats compatible with Github actions, I came across this repository.
Seems this is what I want but I cannot figure out what are these variables & how/where do I get them:
ONE_REPORT_PROJECT_ID
ONE_REPORT_REFRESH_TOKEN
ONE_REPORT_URL

Any help would be appreciated.
Thanks

**Comment by aslakhellesoy** [comment]
Hello @AnujaKadloor

For questions about TestComplete, please use [this forum](https://community.smartbear.com/t5/TestComplete/ct-p/TestComplete_forum).

The `one-report-publisher` tool is not intended to be used with TestComplete.
